version: 2.0

jobs:
  'lint':
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn install
      - run:
          name: Run tests
          command: yarn lint

  'build':
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn install
      - run:
          name: Run build
          command: yarn build

workflows:
  version: 2
  build:
    jobs:
      - 'lint'
      - 'build'
