name: CI

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17'

      - name: run CI nextjs
        run: |
          cd nextjs
          npm install
          npm run lint
