name: Gatsby App CI

on: [push]

jobs:
  gatsby:
    name: Gatsby Job
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Run Scripts
        run: |
          cd gatsby
          yarn install
          yarn lint
          yarn test
          yarn build
