name: Gatsby App CI

on: [push]

jobs:
  nextjs:
    name: NextJS CI
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17'

      - name: Run CI
        run: |
          cd nextjs
          npm install
          npm run lint
          npm run build

  gatsby:
    name: Gatsby CI
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Run CI
        run: |
          cd gatsby
          yarn install
          yarn lint
          yarn test
          yarn build
